import { auth } from '@/lib/firebase';

export interface HealthInsight {
  title: string;
  description: string;
  priority: 'low' | 'medium' | 'high';
  category: 'prevention' | 'analysis' | 'recommendation';
}

export const intelligenceService = {
  /**
   * Fetches proactive health insights generated by AI.
   */
  getPersonalizedInsights: async (): Promise<HealthInsight[]> => {
    const user = auth.currentUser;
    if (!user) return [];

    const token = await user.getIdToken();
    const response = await fetch('/api/intelligence/insights', {
      headers: {
        'Authorization': `Bearer ${token}`
      }
    });

    if (!response.ok) {
      if (response.status === 403) throw new Error("UPGRADE_REQUIRED");
      throw new Error("Failed to fetch intelligence insights");
    }

    const data = await response.json();
    return data.insights || [];
  },

  /**
   * Fetches health trend data for visualization.
   */
  getHealthTrends: async () => {
    const user = auth.currentUser;
    if (!user) return null;

    const token = await user.getIdToken();
    const response = await fetch('/api/intelligence/trends', {
      headers: {
        'Authorization': `Bearer ${token}`
      }
    });

    if (!response.ok) throw new Error("Failed to fetch intelligence trends");

    const data = await response.json();
    return data.trends;
  }
};
